### ISSUE TITLE
add missing timegated recipes to is_timegated?

### ISSUE THREAD

**Issue by solstice-gw2** [t-mw/gw2-arbitrage#2]
For the past couple days, the [Dragon Hatchling Doll Frame](https://wiki.guildwars2.com/wiki/Dragon_Hatchling_Doll_Frame) has been appearing in the general output from gw2-arbitrage.  That's a time-gated recipe (daily), but it's not included in the list of ```output_item_id```s in ```is_timegated```, so it's output even when ```-t``` is not passed to gw2-arbitrage.

Would you be interested in a patch that adds all the remaining ```output_item_id``` from the wiki Category for [time-gated recipes](https://wiki.guildwars2.com/wiki/Category:Time_gated_recipes) ?  That type of patch should be simple enough for me to get right.

Thanks!

solstice.1847

**Comment by t-mw** [comment]
Yes, that would be perfect! I don't think there was a good reason for missing it.
