### ISSUE TITLE
Question re line of code

### ISSUE THREAD

**Issue by Iiridayn** [t-mw/gw2-arbitrage#37]
`tp_prices_map.get_mut(&49429).unwrap().sells.unit_price = 6333;` in `src/main.rs` - deliberate, or left in debugging code? https://api.guildwars2.com/v2/items?id=49429 shows it's a +6 agony infusion

**Comment by t-mw** [comment]
Thanks, removed it in https://github.com/t-mw/gw2-arbitrage/commit/7b7fd7402b20b9a17b872e12e749a12ceeabe687
