### ISSUE TITLE
no longer possible to filter by discipline

### ISSUE THREAD

**Issue by rav550** [t-mw/gw2-arbitrage#4]
Hey, thanks for creating such an awesome tool!

In the previous version, it was possible to filter recipes by discipline by modifying the list in main.rs:

```
<!--StartFragment-->const FILTER_DISCIPLINES: &amp;[&amp;str] = &amp;[
      
      
            "Armorsmith",
      
      
            "Artificer",
      
      
            "Chef",
      
      
            "Huntsman",
      
      
            "Jeweler",
      
      
            "Leatherworker",
      
      
            "Scribe",
      
      
            "Tailor",
      
      
            "Weaponsmith",
      
      
        ]; <span class="pl-c">// only show items craftable by these disciplines</span><!--EndFragment-->
```

Now that the program is an executable, I no longer see a way to modify the list, and exporting to CSV and filtering the list each time is cumbersome. Is it possible to add this back in as a cmd line option, or to read in a config file to filter disciplines?

**Comment by t-mw** [comment]
Thanks, that's a good point! I've just published a new version (0.4.0) with a filter option (e.g. `--disciplines=Weaponsmith,Armorsmith`). Let me know if that works for you.
