### ISSUE TITLE
Use a well-defined location for 'recipes.bin'/'items.bin'

### ISSUE THREAD

**Issue by tildebyte** [t-mw/gw2-arbitrage#6]
My rust skills are non-existent, but, starting at https://github.com/t-mw/gw2-arbitrage/blob/c01ca2be0f661f7253e87c68208cd44bb01d8a46/src/main.rs#L98

I've been using

```diff
-    let recipes_path = "recipes.bin";
-    let items_path = "items.bin";
+    let data_path = "/home/FOO/.local/share/gw2-arbitrage";
+    let recipes_path = format!("{}recipes.bin", data_path);
+    let items_path = format!("{}items.bin", data_path);
```

This allows putting the `gw2-arbitrage` executable anywhere on the path, which I find more convenient than running from the source directory :)

**Comment by t-mw** [comment]
Good idea, how about putting them in `$HOME/.cache/gw2-arbitrage` by default, and providing a `--cache-dir` option to override it? I can add it soon, there are some other small changes to the structure of those files that I want to make at the same time.

**Comment by tildebyte** [comment]
Excellent idea 🚀

**Comment by t-mw** [comment]
This is added in v0.6.0, let me know if it works for you.

**Comment by tildebyte** [comment]
👍

**Comment by tildebyte** [comment]
Boss! Works like a charm :)

**Comment by t-mw** [comment]
Awesome, thanks!
