### ISSUE TITLE
Include non-API recipes

### ISSUE THREAD

**Issue by Iiridayn** [t-mw/gw2-arbitrage#7]
https://github.com/gw2efficiency/custom-recipes is a good source which aggregates wiki data; might be easy to integrate since it's JSON formatted.

**Comment by Iiridayn** [comment]
Current status of this one: unless fixing things like the Steam Minotaur or Endless Gift Dolyak Tonic on this ticket (might be worth another one for those), this seems to be working pretty solidly. Going to close this one.

**Comment by t-mw** [comment]
Created https://github.com/t-mw/gw2-arbitrage/issues/19 for opting out of mystic forge recipes.
